sudo: required
services:
  - docker


before_install:
  - docker build -t mohhus60/docker-react -f Dockerfile.dev .

script:
  - docker run mohhus60/docker-react npm run test -- --coverage
deploy:
   provider: elasticbeanstalk
   region: "us-east-1"
   app: "docker-react"
   env: "DockerReact-env"
   bucket_name: "elasticbeanstalk-us-east-1-416076689372"
   bucket_path: "docker-react"
   on:
     branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key:
     secure: "$AWS_SECRET_KEY"


